//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, serde::Serialize, serde::Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "article_type")]
pub enum ArticleType {
    #[sea_orm(string_value = "ANNOUNCEMENT")]
    Announcement,
    #[sea_orm(string_value = "FULLPAGE")]
    Fullpage,
    #[sea_orm(string_value = "NORMAL")]
    Normal,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, serde::Serialize, serde::Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "user_status")]
pub enum UserStatus {
    #[sea_orm(string_value = "ADMINISTRATOR")]
    Administrator,
    #[sea_orm(string_value = "AUTHOR")]
    Author,
    #[sea_orm(string_value = "COADMINISTRATOR")]
    Coadministrator,
    #[sea_orm(string_value = "HIGHAUTHOR")]
    Highauthor,
}

impl From<String> for UserStatus {
    fn from(value: String) -> Self {
        if value == String::from("Administrator") {
            return Self::Administrator
        }
        else if value == String::from("Coadministrator") {
            return Self::Coadministrator
        }
        else if value == String::from("Highauthor") {
            return Self::Highauthor
        }
        else if value == String::from("Author") {
            return Self::Author
        }
        else {
            panic!("Wrong input.")
        }
    }
}